#!/bin/bash
echo 脚本最后更新时间为10/8/2022

#脚本需要fastp sra-tools fastqc multiqc star rsem（确保二者的index都已经做好了,放在main下RsemIndex)
#截止脚本最后更新时间10.8，各软件版本为(没有指明就是用conda装的）
#sra-tools是下的官网的3.0
#fastp是0.23.2
#star是2.7
#rsem是1.3.3
#fastqc是0.11.9
#multiqc是1.13

#载入库文件
. $cunfang/scck


#下载数据的检查要严格点，并且设置延时




let jl=$2-$1
b=-100
#dump
if [ $1 == 1 ]
then
	Dcheck Dump
        if [ $yc -ne 0 ];
        then
		Yichang
                continue
        fi
       	if [ $1 == 1 ]
        then
                let b=$jl-1
        else
                let b=$b-1
        fi
fi	
#qc
if [ $1 == 2 -o $b -ge 0 ]
then
	Dcheck Qc
	
	if [ $yc == 0 ]
	then
		if [ -e ${main}/${proj}/data/$x*sra* ];then
			rm ${main}/${proj}/data/fqdata/$x* -r
		fi
	else
		Yichang
		continue
	fi
	
	if [ $1 == 2 ]
	then 
		let b=$jl-1
	else
		let b=$b-1
	fi
fi

#star rsem
if [ $1 == 3 -o $b -ge 0 ]
then
	Dcheck StarRsem
        if [ $yc -ne 0 ];
        then
		Yichang
                continue
        fi
        if [ $1 == 3 ]
        then
                let b=$jl-1
        else
                let b=$b-1
        fi
fi

#report
if [ $1 == 4 -o $b -ge 0 ]
then
	echo 开始Fastqc $x
	Dcheck Qreport
	if [ $yc == 0 ];
	then
		rm ${main}/${proj}/qc/$x* -r
	else
		Yichang
		continue
	fi
	echo 完成Fastqc
fi






